# Generated by Django 4.1.3 on 2023-01-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_mensaje_post_imagen_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado_el',
            field=models.DateField(auto_now_add=True),
        ),
    ]
